name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Display PHP version
        run: php -v

      - name: Check composer.json
        run: composer validate

      - name: Composer Install
        run: composer install

      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./"
          target: ${{ secrets.FOLDER }}