name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Display PHP version
        run: php -v

      - name: Check composer.json
        run: composer validate