name: Deployment to production

on:
  push:
    branches: [ master ]

jobs:
  testing:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Check PHP files
        run: php -d memory_limit=-1 vendor/bin/phpstan analyse src

  deploy:
    name: Build and deploy
    needs: testing
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev

      - name: Deploy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./"
          target: ${{ secrets.FOLDER }}